### ISSUE TITLE
Sorting on # installs on dashboard not working

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#41]

**Comment by dhanur** [comment]
Great catch. Also, A.C. Electric shows "null" - if they have 0 homes, they shouldn't be showing up on the list, no?

**Comment by ghost** [comment]
Please re-test.  The sort works fine - you may have tried this when I was
pushing new changes to production.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by ghost** [comment]
Null is fixed.  Sorting works.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
Null doesn't seem to be fixed, A.C. Electric still shows up? How are they active if they have 0 homes installed?

**Comment by suniblestephen** [comment]
Yep, I just tested it and it works. It's weird because it was not working
for any of us in the office today when I had them try it, but works now.

-ST

On Wed, Jul 3, 2013 at 6:17 PM, John Bissell notifications@github.comwrote:

> Please re-test. The sort works fine - you may have tried this when I was
> pushing new changes to production.
> 
> John Bissell
> CTO
> 
> Solar Simplified
> 
> Cell: (510) 229-0577
> Skype: john.bissell
> Email: john@sunible.com
> 
> 55 Harrison Street, 3rd Floor
> Oakland, CA 94607
> 
> On Wed, Jul 3, 2013 at 3:24 PM, suniblestephen notifications@github.comwrote:
> 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/solarisbetter/beta/issues/41>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/41#issuecomment-20454510
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by suniblestephen** [comment]
I think this was one that we manually added when we were sorting by sales.
Now that we sort by installs they have don't have anything.

-ST

On Wed, Jul 3, 2013 at 6:19 PM, dhanur notifications@github.com wrote:

> Null doesn't seem to be fixed, A.C. Electric still shows up? How are they
> active if they have 0 homes installed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/41#issuecomment-20454564
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by dhanur** [comment]
In that case we should change the logic to installs. Else, it is wrong.

**Comment by ghost** [comment]
Fresno is a hack.  Stephen cherry picked the installers he wanted in the
Beta.  This is NOT how the site will work normally.

AC Electric would not normally show up because it has 0 installs.  But
we're _forcing_ it and the other 24 installers to show up for the trial.
 If I take out the Fresno trial restriction, we are going to get a
different and changing group of active installers.

If AC Electric is bothering you guys, I'll just remove it from the original
list and it won't show up at all.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by suniblestephen** [comment]
I am sure it was because I was doing a production push.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by suniblestephen** [comment]
Since we hope to roll our to all of CA soon, would it make more sense to
use the same logic for all areas (Fresno included)?

-ST

On Wed, Jul 3, 2013 at 6:33 PM, John Bissell notifications@github.comwrote:

> Fresno is a hack. Stephen cherry picked the installers he wanted in the
> Beta. This is NOT how the site will work normally.
> 
> AC Electric would not normally show up because it has 0 installs. But
> we're _forcing_ it and the other 24 installers to show up for the trial.
> If I take out the Fresno trial restriction, we are going to get a
> different and changing group of active installers.
> 
> If AC Electric is bothering you guys, I'll just remove it from the
> original
> list and it won't show up at all.
> 
> John Bissell
> CTO
> 
> Solar Simplified
> 
> Cell: (510) 229-0577
> Skype: john.bissell
> Email: john@sunible.com
> 
> 55 Harrison Street, 3rd Floor
> Oakland, CA 94607
> 
> On Wed, Jul 3, 2013 at 6:19 PM, dhanur notifications@github.com wrote:
> 
> > Null doesn't seem to be fixed, A.C. Electric still shows up? How are
> > they
> > active if they have 0 homes installed?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/solarisbetter/beta/issues/41#issuecomment-20454564>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/41#issuecomment-20454920
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by dhanur** [comment]
We will have to accommodate both Logic and Manual overrides.

Logic = installers with given threshold of installs in given timeframe.
Manual Overrides = other installers who request onboarding / upcoming newbies (like Vivint or whoever) / special cases (like Cinnamon Solar)

-DG
On July 3, 2013 at 6:36:16 PM, suniblestephen (notifications@github.com) wrote:

Since we hope to roll our to all of CA soon, would it make more sense to  
use the same logic for all areas (Fresno included)?  

-ST  

On Wed, Jul 3, 2013 at 6:33 PM, John Bissell notifications@github.comwrote:  

> Fresno is a hack. Stephen cherry picked the installers he wanted in the  
> Beta. This is NOT how the site will work normally.  
> 
> AC Electric would not normally show up because it has 0 installs. But  
> we're _forcing_ it and the other 24 installers to show up for the trial.  
> If I take out the Fresno trial restriction, we are going to get a  
> different and changing group of active installers.  
> 
> If AC Electric is bothering you guys, I'll just remove it from the  
> original  
> list and it won't show up at all.  
> 
> John Bissell  
> CTO  
> 
> Solar Simplified  
> 
> Cell: (510) 229-0577  
> Skype: john.bissell  
> Email: john@sunible.com  
> 
> 55 Harrison Street, 3rd Floor  
> Oakland, CA 94607  
> 
> On Wed, Jul 3, 2013 at 6:19 PM, dhanur notifications@github.com wrote:  
> 
> > Null doesn't seem to be fixed, A.C. Electric still shows up? How are  
> > they  
> > active if they have 0 homes installed?  
> > 
> > —  
> > Reply to this email directly or view it on GitHub<  
> > https://github.com/solarisbetter/beta/issues/41#issuecomment-20454564>  
> > .  
> 
> —  
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/41#issuecomment-20454920  
> .  

## 

_Stephen D. Torres_  
Founder & CEO  

Solar Simplified  

55 Harrison Street, 3rd Floor  
Oakland, CA 94607  

Office: (800) 979-2215 Ext.101  
Mobile: (925) 518-9133  
Skype: stephen.d.torres  
LinkedIn: stephendtorres http://www.linkedin.com/in/stephendtorres  
stephen@sunible.com
